from utils.colors import DARK_GRAY

SCREEN_WIDTH = 900
SCREEN_HEIGHT = 675
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
BACKGROUND_COLOR = DARK_GRAY
FPS = 60
SQUARE_WIDTH = 30
SQUARE_HEIGHT = SQUARE_WIDTH
FIRST_COORDS = (0, 0)
PAUSED_SCREEN_ALPHA = 23
PAUSE_WIDTH = 210
PAUSE_HRIGHT = 210
X_COORD_PAUSE = 386
Y_COORD_PAUSE = 273
X_COORD_RESTART = 611
Y_COORD_RESTART = 273
X_COORD_MUSIC = 161
Y_COORD_MUSIC = 273
X_COORD_CLICK_BANNER = 232
Y_COORD_CLICK_BANNER = 430
